### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by xchiex17** [chainer/onnx-chainer#15]
Hi, I installed onnx-chainer along with https://github.com/chainer/onnx-chainer/blob/master/README.md.
I use Ubuntu 16.04.3 LTS, pyenv, and anaconda3-4.1.1.
In my environment, I need to write CPATH as ` export CPATH="/home/[USERAME]/.pyenv/versions/anaconda3-4.1.1/pkgs/protobuf-3.5.1-py35_3/include/"` to successfully perform `pip install git+git://github.com/onnx/onnx.git@8d0fc40162e0df1d14a0eba9e9696568153e54fd` command.
When I didn't write CPATH, this error occured as below:
```    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-v6otrtle-build -I/tmp/pip-v6otrtle-build/third_party/pybind11/include -I/home/chie_furusawa/.pyenv/versions/anaconda3-4.1.1/include/python3.5m -I/home/chie_furusawa/.pyenv/versions/anaconda3-4.1.1/include/python3.5m -c /tmp/pip-v6otrtle-build/onnx/onnx.pb.cc -o build/temp.linux-x86_64-3.5/tmp/pip-v6otrtle-build/onnx/onnx.pb.o -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /tmp/pip-v6otrtle-build/onnx/onnx.pb.cc:4:0:
    /tmp/pip-v6otrtle-build/onnx/onnx.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

Perhaps if he or she uses conda with pyenv, CPATH may not be set.
If you write about this on README.md, he or she may be helped.

I finally could install, so I have no problem.
I hope this will help.

**Comment by mitmul** [comment]
Thank you for sharing the instruction! Actually, the instruction for onnx installation written in [INSTALL.md](https://github.com/chainer/onnx-chainer/blob/master/INSTALL.md) is old. I'll update the information. Please follow the official instruction found in onnx/onnx here: https://github.com/onnx/onnx#installation
Basically, the problems around installing onnx itself is not related to this package (onnx-chainer), but I know I have to care about it because it's a dependency.
